update

diff --git a/bin/colorpicker b/bin/colorpicker
--- a/bin/colorpicker
+++ b/bin/colorpicker
@@ -1,28 +1,32 @@
-#!/usr/bin/env bash
+#!/bin/bash
 
-#   ██╗  ██╗ ██████╗ ██████╗ ██╗      ██████╗ ██████╗
-#   ╚██╗██╔╝██╔════╝██╔═══██╗██║     ██╔═══██╗██╔══██╗
-#    ╚███╔╝ ██║     ██║   ██║██║     ██║   ██║██████╔╝
-#    ██╔██╗ ██║     ██║   ██║██║     ██║   ██║██╔══██╗
-#   ██╔╝ ██╗╚██████╗╚██████╔╝███████╗╚██████╔╝██║  ██║
-#   ╚═╝  ╚═╝ ╚═════╝ ╚═════╝ ╚══════╝ ╚═════╝ ╚═╝  ╚═╝
-# color picker for X.
-# Simple Script To Pick Color Quickly Using Gpick.
-# Created By: https://github.com/rxyhn
+# requieres gpick xclip imagemagick
 
 TEMP_DIR=/tmp/xcolor
 
-main() {
+[ ! -d $TEMP_DIR ] && mkdir -p $TEMP_DIR
 
-	HEX_COLOR=$(gpick -pso --no-newline)
-	mkdir -p $TEMP_DIR
-	HEX="${HEX_COLOR#\#}"
-	FNAME="$TEMP_DIR/$HEX.png"
-	convert -size 100x100 xc:"$HEX_COLOR" "$FNAME"
-	COLOR_CODE="$HEX_COLOR"
-
-	printf %s "$COLOR_CODE" | xclip -sel c
-	dunstify -u normal -i "$FNAME" "$COLOR_CODE" "Copied to clipboard"
+abort() {
+  dunstify -a "Color Picker info" -i dialog-error "Color Picker" "aborted"
+  exit 1
 }
 
-main
+pick() {
+  
+  HEX_COLOR=$(gpick -pso --no-newline)
+
+  [[ -z $HEX_COLOR ]] && abort
+
+  HEX="${HEX_COLOR#\#}"
+  FNAME="$TEMP_DIR/$HEX.png"
+
+  convert -size 100x100 xc:"$HEX_COLOR" "$FNAME"
+
+  COLOR_CODE="$HEX_COLOR"
+
+  echo "$COLOR_CODE" | tr -d '\n' | xclip -sel c
+
+  dunstify -u low -a "Color Picker" -i "$FNAME" $COLOR_CODE "Copied to clipboard"
+}
+
+pick
diff --git a/bin/dripshot b/bin/dripshot
--- a/bin/dripshot
+++ b/bin/dripshot
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 
 DATE="$(date +'%d-%m-%y_%H:%M:%S')"
 DIR="$HOME/Pictures/screenshots"
@@ -7,25 +7,25 @@ PIC="$DIR/$DATE.png"
 [ ! -d "$DIR" ] && mkdir -pv "$DIR"
 
 full() {
-	maim -u "$PIC"
+  maim -u "$PIC"
 }
 crop() {
-	maim --select "$PIC"
+  maim --select "$PIC"
 }
 abort() {
-	dunstify -i dialog-error "Error" "something went wrong"
-	exit 1
+  dunstify -u low -a "Screenshot info" -i dialog-error "Screenshot" "aborted"
+  exit 1
 }
 
 case "$1" in
-full)
-	full || abort
-	xclip -selection c -t image/png "$PIC"
-	dunstify -u normal -i "$PIC" "Copied to clipboard" $PIC
-	;;
-crop)
-	crop || abort
-	xclip -selection c -t image/png "$PIC"
-	dunstify -u normal -i "$PIC" "Copied to clipboard" $PIC
-	;;
+--full)
+  full || abort
+  xclip -selection c -t image/png "$PIC"
+  dunstify -u low -a Screenshot -i "$PIC" "Copied to clipboard" "$PIC"
+  ;;
+--crop)
+  crop || abort
+  xclip -selection c -t image/png "$PIC"
+  dunstify -u low -a Screenshot -i "$PIC" "Copied to clipboard" "$PIC"
+  ;;
 esac
